services:
  api:
    build:
      context: ../
      args:
        CONFIG_PATH: config/prod.yaml
    container_name: reg-api
    ports:
      - "8400:8400"
    networks:
      - reg-web-api

networks:
  reg-web-api:
    driver: bridge
